[tool.poetry]
name = "nb-oai-pmh-metadata"
version = "0.1.0"
description = ""
authors = ["Lars Magne Tungland <larsmtungland@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
